### PR TITLE
List value labels that do not match pattern

### LINKED ISSUE #10: List value labels that do (not) contain a target pattern or set of characters
## Problem

Survey Solutions exports data with value labels that match the answer option text provided in Designer--and for the target translation. In most cases, that is exactly what is wanted. In some cases, value labels may need to be checked for (un)desirable content. For some cases, this entails looking for non-English characters or recurrent non-English phrases (e.g. "oui"/"non" instead of "yes"/"no").

## Implementation ideas

For a command tentatively named `lbl_list_matching_vals`:

- Identify all variables with value labels via `ds, has(vallabel)`
- Create a frame of value labels via `uselabel`
- Filter to entries that match a (regex) pattern
- Report on labels containing (un)desirable content
- Return list of labels in `r(val_lbl_list)` and of variables with those labels in `r(varlist)`

Provide options:

- `negate`. Returns complement of those matching (i.e., inverts result)
- `verbose`. Determines whether reporting is verbose of spartan.

Provide, potentially as other functions curated patterns. For example:

- French characters
- French words (e.g., oui, non)
- HTML characters (e.g., `&amp;`, `&lt;`, `&gt;`)
- Amharic characters

### PR DESCRIPTION
**Pull request by arthur-shaw**
Closes #10 

@kbjarkefur , beyond checking this generally, could you help me troubleshoot an issue? For some reason, I cannot create an `sthlp` file for this command. When I use `ad_sthlp, adf()` to do so, I get the following error message:

```
. ad_sthlp, adf("${clone}")
too few quotes
r(132);
```

I suspect that either my md file is malformed or that adodown isn't handling md files properly that incline quotes (e.g., strings in the examples).

### CODE REVIEW

**Comment by kbjarkefur** [comment]
I can look at this tomorrow. But I am aware of a bug that generates this error when the last character of a line is: ` (a back tick).

I should fix this, but I have prioritized working on the packages, since a full stopp or some rephrasing can easily avoid this.

**Comment by arthur-shaw** [comment]
> I can look at this tomorrow. But I am aware of a bug that generates this error when the last character of a line is: ` (a back tick).
> 
> I should fix this, but I have prioritized working on the packages, since a full stopp or some rephrasing can easily avoid this.

That was it. I added a non ` character to the end of a line in code block in [69382de](https://github.com/lsms-worldbank/labeller/pull/21/commits/69382deacbed7af70bc26baccc657102987f085d)

**Comment by kbjarkefur** [comment]
@arthur-shaw , in 200315650dc505404ded0ef56ba1978ca6ebfef1 I changed the option abbreviations. Since `varlist()` is allowed to be abbreviated as in `Varlist` in all other commands in this package I thought it was best to do that here as well. So I changed `Verbose` to `VERbose`. 

Let me know if you did not want me to do this and I am happy to revert. Otherwise this is ready to merge.

**Comment by arthur-shaw** [comment]
Good call. I'm always in favor of consistency.

**Pull request merged**
