### PR TITLE
Update `pkg` details for ssc publication

### PR DESCRIPTION
**Pull request by arthur-shaw**
This PR revises the following metadata in the `pkg` file:

- Title
- Description
- Keywords

For the title, I lightly modified the existing.

For the description, I tried to:

- Give a broad overview of what the pacakge does: list, label, assert
- Describe what it does for variable and value labels, respectively.

For the keywords, I did the following:

- Looked for label packages on ssc by `ssc describe l`
- Looked at details for a few

### CODE REVIEW

**Comment by arthur-shaw** [comment]
@kbjarkefur , what do you think ?

**Comment by kbjarkefur** [comment]
This looks good!

The only difference I made was to manually cap each line to 120 characters. When you do `net describe labeller, from(C:\Users\wb462869\github\labeller\src)` then the content of this file is displayed, but this content renders with no smart line-breaking, so it looks ugly unless you do it yourself. This is something that I think `ad_publish` should be able to do eventually.

When working on `ad_pulbish` I actually intentionally removed replaced `name` with `title` to make the files more similar to how SSC sets them up. Can `adodownr` get that same information from the filename? `ad_publish` confirms that the upper case of the filename matches the first part of the title. I left it in now as I have not yet made `ad_publish` throw errors on unexpected content. But the `net describe` does not show properly when keeping it, so we should not allow it eventually.

**Comment by kbjarkefur** [comment]
Merging such that I can draft the releases.

**Comment by arthur-shaw** [comment]
> The only difference I made was to manually cap each line to 120 characters. When you do `net describe labeller, from(C:\Users\wb462869\github\labeller\src)` then the content of this file is displayed, but this content renders with no smart line-breaking, so it looks ugly unless you do it yourself. This is something that I think `ad_publish` should be able to do eventually.

Thanks for thinking about this! 

Could we lean on any OS tools for this? On Unix systems, there's [fold](https://askubuntu.com/questions/1398716/how-to-break-string-into-n-80-character-lines). Or would this need to be implemented in Stata (e.g., read the lines, segment the line into less than 80 character blocks, re-write the file)?

> When working on ad_pulbish I actually intentionally removed replaced name with title to make the files more similar to how SSC sets them up. Can adodownr get that same information from the filename? ad_publish confirms that the upper case of the filename matches the first part of the title. I left it in now as I have not yet made ad_publish throw errors on unexpected content. But the net describe does not show properly when keeping it, so we should not allow it eventually.

Definitely. Could I reasonably rely on the name of the `pkg` file? If not the package file, could you think of other places I could grab this (e.g., parse the title line, set everything to lower case and assume pakcage names don't use mixed case)?

**Comment by kbjarkefur** [comment]
> Could we lean on any OS tools for this? On Unix systems, there's [fold](https://askubuntu.com/questions/1398716/how-to-break-string-into-n-80-character-lines). Or would this need to be implemented in Stata (e.g., read the lines, segment the line into less than 80 character blocks, re-write the file)?

Possibly, but I think Stata integrates unreliably with other tools. And this is very easy to implement in `ad_publish`, so the risk-reward-opportunitycost equation makes me have a preference to solve this in `ad_publish`.

**Comment by kbjarkefur** [comment]
> Definitely. Could I reasonably rely on the name of the pkg file? If not the package file, could you think of other places I could grab this (e.g., parse the title line, set everything to lower case and assume pakcage names don't use mixed case)?

I continued the discussion in (https://github.com/lsms-worldbank/adodownr/issues/27), but let me answer your specific question here. `ad_publish` tests that package file name is the same as title. I don't see the title as being more reliable as Stata requires no specific format. `ad_publish`'s checks aside, this means that parsing the title line is much more unreliable than the file name. So an `adodown` package require a format on the title. Stata has lax requirements on the name of the `pkg` file. The name of that file is used in `adoupdate`. Although its not a strict requirement, and I am not sure if all Stata packages follows it.

**Pull request merged**
