### PR TITLE
Redraft README in style of R package

### LINKED ISSUE #24: Improve README
Make a few improvements largely patterned after R/pkgdown conventions. In particular:

- [x] Add hex, pkgdown-style. See [here](https://github.com/arthur-shaw/susoapi/blob/f878729a77fc472bd3547a91ae35cc358f7a0128/README.md?plain=1#L4)
- [x] Add experimental badge. See [here](https://github.com/lsms-worldbank/susometa/blob/c63d5b6ed995b20e9ed6e327606237053fbe326f/README.md?plain=1#L9).
- [x] Add installation heading and instructions
- [x] Add goals/objectives of package. See [here](https://github.com/arthur-shaw/susoapi/blob/f878729a77fc472bd3547a91ae35cc358f7a0128/README.md?plain=1#L9)
- [x] Add a small usage section--a super svelte version of a getting started vignette. See [here](https://github.com/arthur-shaw/susoapi/blob/f878729a77fc472bd3547a91ae35cc358f7a0128/README.md?plain=1#L25)

### PR DESCRIPTION
**Pull request by arthur-shaw**
Closes #24

### CODE REVIEW

**Comment by kbjarkefur** [comment]
I like these edits, but I think it is also nice to have the table of all commands and the link to their web-documentation. 

It both:
* Promotes the adodown web-documentation from the the README when browsing the repo
* Makes it easier for a user to understand how to use this page https://lsms-worldbank.github.io/labeller/ the first time they navigate to it

Can we re-introduce the table somehow? We can split it up based on list/fix/assert purposes, if you want. For the reasons above I would prefer that the table is quite prominent. I do not dare to count on the Stata community to scroll to read documentation carefully enough that they regardless will find what we want them to find.

Let me know what you think.

**Comment by arthur-shaw** [comment]
I'm not averse to this.

However, a few questions on how:

- How would we create the table? Would it be automatically generated (e.g., adodown(r) writes a section to the README)? Would we maintain it manually?
- Where would the table be? In the local Stata docs? In the online documentation? In both?

Just FYI, [here's ](https://github.com/lsms-worldbank/adodownr/issues/16) where I'd like to move in the future for compilations of functions.

**Comment by kbjarkefur** [comment]
> How would we create the table? Would it be automatically generated (e.g., adodown(r) writes a section to the README)? Would we maintain it manually?

So far I have been updating this manually. Automatically would be better and should be the long-term goal, but I am not see how to get there. 

I am a bit worried about `adodown(r)` writing to the README.md file. If a team manually edits their README.md to their preferences, how would `adodown(r)` preserve their manual edits at the same time as it add the automatically generated table?

I would be more comfortable with `adodownr` writing only to this page https://lsms-worldbank.github.io/labeller/ (which is based on README.md) but does not do a git commit to the README.md on the repo. But not sure how to do that. 

The content of the table is to me straightforward to extract. It would be this line in the `# title` section:

https://github.com/lsms-worldbank/labeller/blob/a8d04b34bb1083e7c55566bb9b0fe596dee6bf22/src/mdhlp/lbl_assert_no_long_varlbl.md?plain=1#L3

> Where would the table be? In the local Stata docs? In the online documentation? In both?

I do not see a place in the Stata docs where this would fit. So I am thinking only web docs.

---

I agree with what everything you are saying here and in the places you link to. I think you are spot on how to best generate the index (or part of the index) automatically. But I am still stuck in questions such as, which index, if any, should we generate automatically? And if we generate an index automatically, would we allow manual contribution to the index as well? If so, how would the workflow for that be?

**Comment by arthur-shaw** [comment]
> So far I have been updating this manually. Automatically would be better and should be the long-term goal, but I am not see how to get there.
>
> I am a bit worried about adodown(r) writing to the README.md file. If a team manually edits their README.md to their preferences, how would adodown(r) preserve their manual edits at the same time as it add the automatically generated table?
>
> I would be more comfortable with adodownr writing only to this page https://lsms-worldbank.github.io/labeller/ (which is based on README.md) but does not do a git commit to the README.md on the repo. But not sure how to do that.

You're exactly right on this. If this were an R package, the workflow would be to write README.Rmd that writes README.md, such that R/RMarkdown does some of mundane work for us. For the future, not sure if we could think of a comparable workflow with Stata's dyndoc framework.

> I agree with what everything you are saying here and in the places you link to. I think you are spot on how to best generate the index (or part of the index) automatically. But I am still stuck in questions such as, which index, if any, should we generate automatically? And if we generate an index automatically, would we allow manual contribution to the index as well? If so, how would the workflow for that be?

My proposal is to have adodownr create the reference index for us. At present, it creates a table whose contents are alphabetically ordered by command name. Based on work in the draft PR, I think we can have it generate a custom reference index page. The user contributions would only be through how the user sets up the titles, subtitles, descriptions, and groupings of commands. The command name and description would continue to come from the `md` help files without modification.

See image below. The user would simply structure/tweak their reference index page through yaml using the same system as pkgdown does. Here's an example crudely sketched for labeller as a test.
[reference_index.zip](https://github.com/lsms-worldbank/labeller/files/14195716/reference_index.zip)

image

**Comment by arthur-shaw** [comment]
@kbjarkefur , in Markdown--and gfm README's in particular--can one have a child document? In case the term isn't established outside of RMarkdown, [here's ](https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html) a primer. In our case, I'm thinking of a table that adodownr could write in a separate `md` file but whose contents would be included/imported into `README.md`.

I'm seeing a messy, qualified "yes" [here](https://stackoverflow.com/questions/4779582/markdown-and-including-multiple-files/).

**Comment by kbjarkefur** [comment]
> @kbjarkefur , in Markdown--and gfm README's in particular--can one have a child document? 

In pure md there is no runtime support for this. As in, the pure md protocol  for rendering markdown does not have support for any other other support from typesetting pure md syntax to whatever is needed for it to render (often html tags but not always).

That's where Rmd, Qmd, pandoc etc, comes in. In different ways, they add runtime with support for much more before the md renders. 

So this is very possible, the question is just what makes most sense to the Stata community.

**Comment by arthur-shaw** [comment]
So possible in principle, but problematic in practice. Unless you see any clean solution that won't overcomplicate use for the Stata community, I propose that we continue to maintain the table in the README manually, while keeping this as a potential quality-of-life feature for the future. Sound right?

**Comment by kbjarkefur** [comment]
> So possible in principle, but problematic in practice. Unless you see any clean solution that won't overcomplicate use for the Stata community, I propose that we continue to maintain the table in the README manually, while keeping this as a potential quality-of-life feature for the future. Sound right?

Agreed!

**Pull request merged**
