### PR TITLE
Create commands to check variable label length

### LINKED ISSUE #3: Flag variables that might be truncated (i.e., at 80 character max)
## Problem

Survey Solutions provides variables with a variable label. If provided, Survey Solutions uses the `Variable label` field in Designer, whose length is capped at 80 characters (in line with Stata's limits). If no label is specified in that field, Survey Solutions uses the `Question text field`, whose length maximum length is 2,000 characters. In the latter case, Survey Solutions uses the first 80 characters of the question text as its label.

In light of the rules above for how variable labels are applied by Survey Solutions, labels that are 80 characters long migtht be truncations of the question text.

Hence, it would be useful if one could identify such variables with labels that are the max length and take action, if needed.

## Implementation ideas

There might be better Stata tools or a more elegant algorithm, but here's a crude sketch of how to list variables with lengthy variable labels:

1. Get the list of (all) variables
2. Loop over each variable
3. Extract its variable label via `local var_label : variable label varname`
4. Determine the length of the label via `local var_label_length : strlen local var_label`
5. If the length is 80, then include the variable name in a local that compiles variables whose labels are the max length
6. Return the list of variable with labels of length 80 characters

There could be a few commands associated with this user story:

- `lbl_list_var_max_len`
- `lbl_assert_no_var_max_len`

### PR DESCRIPTION
**Pull request by arthur-shaw**
- lbl_list_var_max_len
- lbl_assert_no_var_max_len

@kbjarkefur , can you think of shorter function names that are still indicative of function?

### CODE REVIEW

**Comment by arthur-shaw** [comment]
Closes #8

**Comment by kbjarkefur** [comment]
I made some fixes. Mostly stylish and other edits that will only have an effect in rare cases. See the commit description for details.

For command names, how about `lbl_list_long_vars` and `lbl_assert_no_long_vars`. Not much shorter, and perhaps a bit less precise, but feels like there is less risk you have to read the names twice to get what they do.

**Comment by kbjarkefur** [comment]
Next I have a question about whether these commands should have the feature to accept a varlist. I can see argument for both sides, and I think there is no objective correct decision. It comes down to what we want this command to be. 

Do we see these as commands as a tool that users should be able to use however flexible they want? Or should these commands be an opinionated tool that certifies something about the full data set? For example, if a user passes a varlist to `lbl_assert_no_var_max_len` then that command does no longer guarantee that there are no long var labels in the dataset. But if we do not allow a varlist we might be restricting the full potential utility. 

I implemented `lbl_list_pipes` without varlist, but my only strong preference is that we are consistent accross the package. There are some fixes can do regardless of what we decide we want.

**Comment by arthur-shaw** [comment]
## Command names

On the command names, inspired by your suggestions, I have a few others.

To avoid repetition of `max_len` (echoed in the `maxlen` option), here are some equally long names:

- lbl_list_long_varlbl
- lbl_assert_no_long_varlbl

To prioritize brevity (at the expense of repetition):

- lbl_list_long_lbl
- lbl_assert_no_long_lbl

And to add two more characters (at the expense, somewhat of brevit, and precision):

- lbl_list_long_label
- lbl_assert_no_long_label

## Allow varlist or not

I'm inclined to offer users the ability to provide a variable list.  I expect that the option will be rarely used, but might be useful for those that would like to use it.

I do, however, appreciate your point that if a varlist is possible that the assertion commands lose their utility as a "your data are OK" seal of approval. 

Perhaps we could address this concern by providing more details in the message printed to the console. In particular, if any varlist is provided, the command should indicate the scope for which the assertion is valid (i.e., the varlist).

What do you think--on both points?

**Comment by kbjarkefur** [comment]
Renamed to:

- lbl_list_long_varlbl
- lbl_assert_no_long_varlbl

And moved varlist to https://github.com/lsms-worldbank/labeller/issues/18

**Pull request merged**
